name = "d3st1ny's Overdrive Client"
author = "d3st1nyOff"
version = "1.02"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0530c9fd8b25ecca427c084eaabc93a494f4b0d423b68b703a1ab61f18a81e84"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.10"
